name: Build SharpGPOAbuse

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: SharpGPOAbuse.sln

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore $env:Solution_Name

      - name: Build solution
        run: msbuild $env:Solution_Name /p:Configuration=${{ matrix.configuration }} /p:Platform="Any CPU" /m

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SharpGPOAbuse-${{ matrix.configuration }}
          path: SharpGPOAbuse/bin/${{ matrix.configuration }}/
          if-no-files-found: error
